:PROPERTIES:
:ID:       c1264a2e-4026-4e15-839b-6ff3999b12cf
:END:
#+title: Mode Bash
#+author: Deden Bangkit

#+PROPERTY: header-args:sh    :exports both
#+PROPERTY: header-args:sh+   :results drawer
#+PROPERTY: header-args:sh+   :noweb strip-export

* Jq

jq is a lightweight and flexible command-line tool for parsing, manipulating, and querying JSON data. It is designed specifically for working with JSON, making it easy to extract specific values, filter data based on conditions, transform data structures, and perform complex operations on JSON documents.

** Map and Limit Value

#+name: Map and Limit Value
#+begin_src sh
curl -s https://www.emsifa.com/api-wilayah-indonesia/api/regencies/32.json \
    | jq 'map({district_id: .id, district_name: .name}) | .[:2]'
#+end_src

#+RESULTS: Map and Limit Value
:results:
[
  {
    "district_id": "3201",
    "district_name": "KABUPATEN BOGOR"
  },
  {
    "district_id": "3202",
    "district_name": "KABUPATEN SUKABUMI"
  }
]
:end:

** Transform Value
#+name: Transform Value
#+begin_src sh :results drawer
echo "| Name | City |"
echo "|-+-|"
curl -s https://www.emsifa.com/api-wilayah-indonesia/api/regencies/32.json \
    | jq -r '.[] | "|" + .id + "|" +  .name + "|"'
#+end_src

#+RESULTS: Transform Value
:results:
| Name | City                    |
|------+-------------------------|
| 3201 | KABUPATEN BOGOR         |
| 3202 | KABUPATEN SUKABUMI      |
| 3203 | KABUPATEN CIANJUR       |
| 3204 | KABUPATEN BANDUNG       |
| 3205 | KABUPATEN GARUT         |
| 3206 | KABUPATEN TASIKMALAYA   |
| 3207 | KABUPATEN CIAMIS        |
| 3208 | KABUPATEN KUNINGAN      |
| 3209 | KABUPATEN CIREBON       |
| 3210 | KABUPATEN MAJALENGKA    |
| 3211 | KABUPATEN SUMEDANG      |
| 3212 | KABUPATEN INDRAMAYU     |
| 3213 | KABUPATEN SUBANG        |
| 3214 | KABUPATEN PURWAKARTA    |
| 3215 | KABUPATEN KARAWANG      |
| 3216 | KABUPATEN BEKASI        |
| 3217 | KABUPATEN BANDUNG BARAT |
| 3218 | KABUPATEN PANGANDARAN   |
| 3271 | KOTA BOGOR              |
| 3272 | KOTA SUKABUMI           |
| 3273 | KOTA BANDUNG            |
| 3274 | KOTA CIREBON            |
| 3275 | KOTA BEKASI             |
| 3276 | KOTA DEPOK              |
| 3277 | KOTA CIMAHI             |
| 3278 | KOTA TASIKMALAYA        |
| 3279 | KOTA BANJAR             |
:end:

** List Specific Key Values

#+name: List Specific Key Value
#+begin_src sh
curl -s https://www.emsifa.com/api-wilayah-indonesia/api/regencies/32.json \
    | jq -r '.[:2] | .[].name'
#+end_src

#+RESULTS: List Specific Key Value
:results:
KABUPATEN BOGOR
KABUPATEN SUKABUMI
:end:

** Filter by Value

#+name: Filter by Value
#+begin_src sh
curl -s https://www.emsifa.com/api-wilayah-indonesia/api/regencies/32.json \
    | jq -r 'map(select(.id > "3277")) | .[].name'
#+end_src

#+RESULTS: Filter by Value
:results:
KOTA TASIKMALAYA
KOTA BANJAR
:end:


* PUP

PUP is a command line tool for processing HTML. It reads from stdin, prints to stdout, and allows the user to filter parts of the page using CSS selectors.

Read more: [[https://github.com/ericchiang/pup]]

** Filter By HTML Tag and ClassName

#+name: Filter by HTML Tag
#+begin_src sh
curl -s https://news.ycombinator.com/ \
    | pup 'span.titleline .sitestr' \
    | head -n 6
#+end_src

#+RESULTS: Filter by HTML Tag
:results:
<span class="sitestr">
 ableton.com
</span>
<span class="sitestr">
 arxiv.org
</span>
:end:

** HTML To JSON

#+name: HTML To JSON
#+begin_src sh
curl -s https://news.ycombinator.com/ \
    | pup 'span.titleline .sitestr json{}' \
    | jq -r ".[:2]"
#+end_src

#+RESULTS: HTML To JSON
:results:
[
  {
    "class": "sitestr",
    "tag": "span",
    "text": "ableton.com"
  },
  {
    "class": "sitestr",
    "tag": "span",
    "text": "arxiv.org"
  }
]
:end:
